builds:
  - binary: askcloud
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: cloud-lens
    homepage: https://github.com/chinmaysomani07/askcloud
    tap:
      owner: chinmaysomani07
      name: homebrew-chinmaysomani07
    commit_author:
      name: chinmaysomani07
      email: chinmaysomani7@gmail.com

checksum:
  name_template: 'checksums.txt'
