builds:
  - goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    env:
      - CGO_ENABLED=0
   
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/chinmaysomani07/askcloud/cmd.version=v{{.Version}}
release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: tempaskcl
    homepage: https://github.com/chinmaysomani07/askcloud
    tap:
      owner: chinmaysomani07
      name: homebrew-askcloud
    commit_author:
      name: chinmaysomani07
      email: chinmaysomani7@gmail.com

checksum:
  name_template: 'checksums.txt'
